#ifndef PIPESCOLLISION_H
#define PIPESCOLLISION_H
int numPipes;
int pipeX[3];
int pipeY[3];
int pipeWidth;
int pipeGap[3];
int pipeSpeed;
void checkCollision();
int isColliding();
int randomGapHeight();
#endif //PIPESCOLLISION_H
